### PR TITLE
Vm selection animation

### PR DESCRIPTION
**Pull request by jniederm**
... polished.

### CODE REVIEW

**Comment by matobet** [comment]
@mareklibra can you please verify this change if we can merge this?

**Comment by jniederm** [comment]
Not tested (userportal is not working for me). This is the idea: http://jsbin.com/pasafihaqe/edit?html,css,output

**Comment by mareklibra** [comment]
The basic idea is working! Thanks.

I'm sending you polished and adapted version in a patch.

**Comment by jniederm** [comment]
Not tested. Again because of "./src/LoginForm.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./styles.css in /home/.../src/userportal/src".

**Review by mareklibra — APPROVED** [review]
Works fine

**Comment by mareklibra** [comment]
This can be merged

**Pull request merged**
