### PR TITLE
Components moved to web-ui

### PR DESCRIPTION
**Pull request by jniederm**

### CODE REVIEW

**Comment by jniederm** [comment]
Please review @matobet @mareklibra @bond95

**Review by mareklibra — APPROVED** [review]
Verified within https://github.com/oVirt/ovirt-web-ui/pull/109.
Can be merged.

Please release new version once merged.

**Comment by matobet** [comment]
@jniederm please also remove from `package.json` all references to the (now non-existent) "showcase" (in the scripts section mainly)

**Comment by matobet** [comment]
@jniederm please also remove the `external` linking dependencies on Redux, React-Redux and Redux saga from `webpack.config.js`

**Comment by jniederm** [comment]
@matobet done

**Pull request merged**
